### PR TITLE
Allow selection with vi keys

### PR DESCRIPTION
**Pull request by afh**
when the VISUAL environment variable is set.

What are your thoughts on this, @humblepenguinn, for a first attempt to please long time vi-users, who mostly deleted the cursor keys from the muscle memory?

### CODE REVIEW

**Comment by humblepenguinn** [comment]
You beat me to it 😅. 

Thank you @afh

**Comment by afh** [comment]
Sorry about that 😉 
I have a [PR out on upstream inquire](https://github.com/mikaelmello/inquire/pull/227) enabling use of `h` and `l` keys to clear the current selection and select all. Maybe you'd like to show your support for the PR if you see value in it for envio?

**Comment by humblepenguinn** [comment]
@afh That sounds like a great idea! I'll definitely show my support

Also I updated your implementation to accept a boolean value only, since currently the user just has to pass the `VISUAL` env with any value. So in the new implementation the `VISUAL` env is parsed and converted to a boolean.

**Comment by afh** [comment]
@humblepenguinn the `VISUAL` environment variable usually holds the command (or path to) that should be used as a visual editor, e.g. `vi` or `vim` or `/usr/bin/vim`. So if envio expects a boolean value, i.e. `true` or `false` that would break with "the UNIX tradition".
I did not want to parse the value of `VISUAL`, because it can be "too complex" for envio and the presence of the environment variable should be indicator enough that the user would appreciate inquire's `vim_mode`…

**Comment by humblepenguinn** [comment]
@afh, well in that case `VISUAL` doesn't seem appropriate in my opinion. Since we don't really care about the visual editor being used, but rather just want a way to figure out if the user want's to use `vim_mode`. 

And neither does inquire, require a visual editor argument but rather a boolean value (`vim_mode`). 

What do you say?

**Comment by humblepenguinn** [comment]
Perhaps we can parse the output of the following command: set -o | grep vi, but it only seems to work when I run set -o vi.

However, I don't see why we need to keep the VISUAL environment variable. We don't need either the vi or the emacs editor path. We just need a way for the user to tell us if they want vim mode enabled in their selection prompts. So, the path to the editor doesn't really matter here.

The Emacs key bindings in the inquire crate are already enabled by default, so we can't provide users the option to opt out from there. Thus, right now, we just need a way to figure out if the user wants vim_mode enabled or not.

I think we should change the name of the environment variable to VI or VI_MODE, and the user has to assign it a boolean value.

**Comment by afh** [comment]
I think I have an idea on how to approach this. Expect a PR soon 🙂

**Comment by afh** [comment]
Please have a look at #53 🙂 Possibly the proposed changes are trying to be too clever, but introducing yet another configuration environment variable specific to a single program does not feel right either…

**Pull request merged**
